### ISSUE TITLE
openwrt替换了1.2.1的启动不起来了

### ISSUE THREAD

**Issue by houpi** [felix-fly/xray-openwrt#2]
i386的openwrt，原来通过ipk安装了1.2.0，然后下载了1.2.1的文件覆盖进去，结果启动不起来了

**Comment by felix-fly** [comment]
有什么错误信息吗？arm64的我试过没问题，理论上其它应该也ok

**Comment by houpi** [comment]
我下的是386那个，换成amd64的可以了
